
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxqpnmlbbzvgcmbdbuzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4cXBubWxiYnp2Z2NtYmRidXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzM2OTQsImV4cCI6MjA2MTY0OTY5NH0.ZuFZrQgDSBoVDs05JO220amxw8s9QSQsK0E8uRW9zhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    db: {
      schema: 'public',
    },
    auth: {
      autoRefreshToken: true,
      persistSession: true,
    },
  }
);
