// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zneajklemxubtxwhjdsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZWFqa2xlbXh1YnR4d2hqZHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjIyNDgsImV4cCI6MjA2MTE5ODI0OH0.TXz5kptX7dOA6ZgX_mN9JdT7BsxEj-dU79vUBk818A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);